project:
  type: website

website:
  navbar:
    logo: 'media/home-icon.svg'
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "1A. Geospatial Data Science with R"
          href: "Hands-on_Ex/Hands-on_Ex01A/Hands-on_Ex01A.html"
        - text: "1B. Thematic Mapping and GeoVisualisation"
          href: "Hands-on_Ex/Hands-on_Ex01B/Hands-on_Ex01B.html"
        - text: "2A. 1st Order Spatial Point Pattern Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02A.html"
        - text: "2B. 2nd Order Spatial Point Pattern Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02B.html"
        - text: "3. Network Constrained Spatial Point Pattern Analysis"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "4. Spatial Weights and Applications"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "5A. Global Measures of Spatial Autocorrelation"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05A.html"
        - text: "5B. Local Measures of Spatial Autocorrelation"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05B.html"
        - text: "6. Geographical Segmentation"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "7. Geographically Weighted Explanatory Models"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
        - text: "8. Geographically Weighted Predictive Models"
          href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
        - text: "9A. Processing & Visualising Flow Data"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09A.html"
        - text: "9B. Calibrating Spatial Interaction Models"
          href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09B.html"
        - text: "10. Modelling Geographical Accessibility"
          href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html" 
    - text: "In-class Exercise"
      menu: 
        - text: "In-class Ex 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "In-class Ex 2"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "In-class Ex 3"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "In-class Ex 4"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In-class Ex 5"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
        - text: "In-class Ex 6"
          href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
        - text: "In-class Ex 7"
          href: "In-class_Ex/In-class_Ex07/In-class_Ex07.html"
        - text: "In-class Ex 8"
          href: "In-class_Ex/In-class_Ex08/In-class_Ex08.html"
        - text: "In-class Ex 9"
          href: "In-class_Ex/In-class_Ex09/In-class_Ex09.html"
        - text: "In-class Ex 10"
          href: "In-class_Ex/In-class_Ex10/In-class_Ex10.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Take-home Ex 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Ex 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take-home Ex 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
    right:
    - icon: github
      href: https://github.com/stephentay/ISSS626-Geospatial-Analytics
    - icon: linkedin
      href: https://www.linkedin.com/in/stephen-tay/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

