project:
  type: website

website:
  navbar:
    logo: 'media/home-icon.svg'
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "1A. Geospatial Data Science with R"
          href: "Hands-on_Ex/Hands-on_Ex01A/Hands-on_Ex01A.html"
        - text: "1B. Thematic Mapping and GeoVisualisation"
          href: "Hands-on_Ex/Hands-on_Ex01B/Hands-on_Ex01B.html"
        - text: "2A. 1st Order Spatial Point Pattern Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02A.html"
        - text: "2B. 2nd Order Spatial Point Pattern Analysis Methods"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02B.html"
        - text: "3. Network Constrained Spatial Point Pattern Analysis"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
    - text: "In-class Exercise"
      menu: 
        - text: "In-class Ex 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "In-class Ex 2"
          href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
        - text: "In-class Ex 3"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Take-home Ex 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
    right:
    - icon: github
      href: https://github.com/stephentay/ISSS626-Geospatial-Analytics
    - icon: linkedin
      href: https://www.linkedin.com/in/stephen-tay/

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

