---
title: "Hands-on Ex 4"
subtitle: "Spatial Weights and Applications"
author: "Stephen Tay"
date: "15 Sep 2024"
date-modified:  "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  warning: false
  freeze: true 
---

# 1. Overview



```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, knitr)
```

# 2. Importing & Transforming Data


```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan") #%>%
  #st_transform(crs = 4549)
```
```{r}
st_crs(hunan)
```

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

8.3.3
```{r}
hunan <- left_join(hunan, hunan2012, by = "County") %>%
  select(1:4, 7, 15)
```

8.4
```{r}
basemap <- tm_shape(hunan) +
  tm_polygons() +
  tm_text("NAME_3", size=0.5)

gdppc <- qtm(hunan, fill = "GDPPC")

tmap_arrange(basemap, gdppc, asp=1, ncol=2)
```

8.5
```{r}
wm_q <- poly2nb(hunan, queen=TRUE)
summary(wm_q)
```


```{r}
wm_q[[1]]
```


```{r}
hunan$County[1]
```


```{r}
hunan$NAME_3[wm_q[[1]]]
```


```{r}
hunan$GDPPC[wm_q[[1]]]
```


```{r}
str(wm_q)
```

8.5.2
```{r}
wm_r <- poly2nb(hunan, queen=FALSE)
summary(wm_r)
```
8.5.3

```{r}
longitude <- map_dbl(hunan$geometry, ~st_centroid(.x)[[1]])
latitude <- map_dbl(hunan$geometry, ~st_centroid(.x)[[2]])
coords <- cbind(longitude, latitude)
```


```{r}
head(coords)
```


```{r}
plot(hunan$geometry, border="lightgrey")
plot(wm_q, coords, pch = 19, cex = 0.6, add = TRUE, col= "red")
```


```{r}
plot(hunan$geometry, border="lightgrey")
plot(wm_r, coords, pch = 19, cex = 0.6, add = TRUE, col = "red")
```


```{r}
par(mfrow=c(1,2))
plot(hunan$geometry, border="lightgrey", main="Queen Contiguity")
plot(wm_q, coords, pch = 19, cex = 0.6, add = TRUE, col= "red")
plot(hunan$geometry, border="lightgrey", main="Rook Contiguity")
plot(wm_r, coords, pch = 19, cex = 0.6, add = TRUE, col = "red")
```

8.6.1
```{r}
#coords <- coordinates(hunan)
k1 <- knn2nb(knearneigh(coords))
k1dists <- unlist(nbdists(k1, coords, longlat = TRUE))
summary(k1dists)
```

8.6.2
```{r}
wm_d62 <- dnearneigh(coords, 0, 62, longlat = TRUE)
wm_d62
```


```{r}
str(wm_d62)
```


```{r}
table(hunan$County, card(wm_d62))
```


```{r}
n_comp <- n.comp.nb(wm_d62)
n_comp$nc
```


```{r}
table(n_comp$comp.id)
```

8.6.2.1
```{r}
plot(hunan$geometry, border="lightgrey")
plot(wm_d62, coords, add=TRUE)
plot(k1, coords, add=TRUE, col="red", length=0.08)
```


```{r}
par(mfrow=c(1,2))
plot(hunan$geometry, border="lightgrey", main="1st nearest neighbours")
plot(k1, coords, add=TRUE, col="red", length=0.08)
plot(hunan$geometry, border="lightgrey", main="Distance link")
plot(wm_d62, coords, add=TRUE, pch = 19, cex = 0.6)
```


```{r}
knn6 <- knn2nb(knearneigh(coords, k=6))
knn6
```


```{r}
str(knn6)
```


```{r}
plot(hunan$geometry, border="lightgrey")
plot(knn6, coords, pch = 19, cex = 0.6, add = TRUE, col = "red")
```

8.7

```{r}
dist <- nbdists(wm_q, coords, longlat = TRUE)
ids <- lapply(dist, function(x) 1/(x))
ids
```

8.8
```{r}
rswm_q <- nb2listw(wm_q, style="W", zero.policy = TRUE)
rswm_q
```


```{r}
rswm_q$weights[10]
```


```{r}
rswm_ids <- nb2listw(wm_q, glist=ids, style="B", zero.policy=TRUE)
rswm_ids
```


```{r}
rswm_ids$weights[1]
```


```{r}
summary(unlist(rswm_ids$weights))
```

8.9.1
```{r}
GDPPC.lag <- lag.listw(rswm_q, hunan$GDPPC)
GDPPC.lag
```


```{r}
nb1 <- hunan$GDPPC[wm_q[[1]]]
nb1
```


```{r}
lag.list <- list(hunan$NAME_3, lag.listw(rswm_q, hunan$GDPPC))
lag.res <- as.data.frame(lag.list)
colnames(lag.res) <- c("NAME_3", "lag GDPPC")
hunan <- left_join(hunan, lag.res)
```


```{r}
head(hunan)
```


```{r}
gdppc <- qtm(hunan, "GDPPC")
lag_gdppc <- qtm(hunan, "lag GDPPC")
tmap_arrange(gdppc, lag_gdppc, asp=1, ncol=2)
```

8.9.2
```{r}
b_weights <- lapply(wm_q, function(x) 0*x + 1)
b_weights2 <- nb2listw(wm_q, 
                       glist = b_weights, 
                       style = "B")
b_weights2
```


```{r}
lag_sum <- list(hunan$NAME_3, lag.listw(b_weights2, hunan$GDPPC))
lag.res <- as.data.frame(lag_sum)
colnames(lag.res) <- c("NAME_3", "lag_sum GDPPC")
```


```{r}
lag_sum
```


```{r}
hunan <- left_join(hunan, lag.res)
```


```{r}
gdppc <- qtm(hunan, "GDPPC")
lag_sum_gdppc <- qtm(hunan, "lag_sum GDPPC")
tmap_arrange(gdppc, lag_sum_gdppc, asp=1, ncol=2)
```

8.9.3
```{r}
wm_qs <- include.self(wm_q)
```


```{r}
wm_qs[[1]]
```


```{r}
wm_qs <- nb2listw(wm_qs)
wm_qs
```


```{r}
lag_w_avg_gpdpc <- lag.listw(wm_qs, 
                             hunan$GDPPC)
lag_w_avg_gpdpc
```


```{r}
lag.list.wm_qs <- list(hunan$NAME_3, lag.listw(wm_qs, hunan$GDPPC))
lag_wm_qs.res <- as.data.frame(lag.list.wm_qs)
colnames(lag_wm_qs.res) <- c("NAME_3", "lag_window_avg GDPPC")
```


```{r}
hunan <- left_join(hunan, lag_wm_qs.res)
```


```{r}
hunan %>%
  select("County", 
         "lag GDPPC", 
         "lag_window_avg GDPPC") %>%
  kable()
```


```{r}
w_avg_gdppc <- qtm(hunan, "lag_window_avg GDPPC")
tmap_arrange(lag_gdppc, w_avg_gdppc, asp=1, ncol=2)
```

8.9.4
```{r}
wm_qs <- include.self(wm_q)
wm_qs
```


```{r}
b_weights <- lapply(wm_qs, function(x) 0*x + 1)
b_weights[1]
```


```{r}
b_weights2 <- nb2listw(wm_qs, 
                       glist = b_weights, 
                       style = "B")
b_weights2
```


```{r}
w_sum_gdppc <- list(hunan$NAME_3, lag.listw(b_weights2, hunan$GDPPC))
w_sum_gdppc
```


```{r}
w_sum_gdppc.res <- as.data.frame(w_sum_gdppc)
colnames(w_sum_gdppc.res) <- c("NAME_3", "w_sum GDPPC")
```


```{r}
hunan <- left_join(hunan, w_sum_gdppc.res)
```


```{r}
hunan %>%
  select("County", "lag_sum GDPPC", "w_sum GDPPC") %>%
  kable()
```


```{r}
w_sum_gdppc <- qtm(hunan, "w_sum GDPPC")
tmap_arrange(lag_sum_gdppc, w_sum_gdppc, asp=1, ncol=2)
```


```{r}

```


```{r}

```
